[screenpen]
; Possible values for areas: topToolBarArea, bottomToolBarArea, leftToolBarArea, rightToolBarArea
penbar_area = rightToolBarArea
boardbar_area = bottomToolBarArea
actionbar_area = rightToolBarArea
hidden_menus = False
icon_size = 20
sc_undo = Ctrl+Z
sc_redo = Ctrl+Y
sc_toggle_menus = Ctrl+1
exit_mouse_button = right
exit_shortcut = Escape
drawing_history = 500